version: "3.7"
services:
  golang-api: 
    container_name: "golang-api"
    build:
      context: .
      dockerfile: api.Dockerfile
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - .:/app/
  db:
    container_name: "mysql"
    platform: linux/x86_64
    volumes:
      - mysql_data:/var/lib/mysql
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - default
    restart: always
    ports:
      - "5000:5000"
    environment:
      MY_SQL_ROOT_PASSWORD: "aragourn2x38"
      MY_SQL_DATABASE: "dclib_test"
      MY_SQL_USER: "dclib_user"
      MY_SQL_PASSWORD: "password_"
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
