version: "3.7"
services:
  golang-api: 
    container_name: "golang-api"
    build:
      context: .
      dockerfile: api.Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app/
    env_file:
      - .env
  db:
    image: mysql:8.0.30
    container_name: "mysql"
    platform: linux/x86_64
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DBPASS}"
      MYSQL_DATABASE: "${DBNAME}"


volumes:
  dbdata:
    driver: local