version: "3.7"
services:
  golang-api: 
    container_name: "golang-api"
    build:
      context: .
      dockerfile: api.Dockerfile
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - .:/app/
  db:
    image: mysql:8.0.30
    container_name: "mysql"
    platform: linux/x86_64
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default
    restart: always
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
