DROP TABLE IF EXISTS books_authors;
DROP TABLE IF EXISTS favoriete_books;
DROP TABLE IF EXISTS favoriete_authors;
DROP TABLE IF EXISTS booking;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS authors;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;



